# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuttl-cli" do
  version "0.27.0"

  on_macos do
    on_intel do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_darwin_x86_64.tar.gz"
      sha256 "114b67fcd1cc6878166c8b7ea8364925ff8effbae7ba80ce375876677879189e"
    end
    on_arm do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_darwin_arm64.tar.gz"
      sha256 "a9b9c09e89f6ecf128a79350b111bea39df84d628e89afc9add5d593137864df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_linux_x86_64.tar.gz"
      sha256 "5a51888ff8a162b4ffe2f32564b8c62d5c0319569ccf6805851554fa1a8ded8b"
    end
    on_arm do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_linux_arm64.tar.gz"
      sha256 "6737b87c7d10bbe60a21347a7ba9a983ad4ba455a8d8990cc9bf749b7f0c8299"
    end
  end

  name "kuttl-cli"
  desc "Interact with KUTTL via the kubectl plugin"
  homepage "https://github.com/kudobuilder/kuttl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kubectl-kuttl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-kuttl"]
    end
  end

  # No zap stanza required

end
