# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuttl-cli" do
  version "0.26.0"

  on_macos do
    on_intel do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_darwin_x86_64.tar.gz"
      sha256 "2ffbf8d3e996a4c077ec09f17a462bc2ad33aad537ce83d3a9d7ed1eb737b804"
    end
    on_arm do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_darwin_arm64.tar.gz"
      sha256 "ac2fd11d770b4082dd3d7462b4c80e5c08d0d619c52f4f34d8e22f9e4c657b02"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_linux_x86_64.tar.gz"
      sha256 "a1e85cf519f19260b16f8c2c77b475c6b43c10313aee1ad02469f37da08dbe86"
    end
    on_arm do
      url "https://github.com/kudobuilder/kuttl/releases/download/v#{version}/kuttl_#{version}_linux_arm64.tar.gz"
      sha256 "f7fe82b0dd18d26a146b7a9158adb927f631be1bf6e387e461277ad41a23220d"
    end
  end

  name "kuttl-cli"
  desc "Interact with KUTTL via the kubectl plugin"
  homepage "https://github.com/kudobuilder/kuttl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kubectl-kuttl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-kuttl"]
    end
  end

  # No zap stanza required

end
