# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KuttlCli < Formula
  desc "Interact with KUTTL via the kubectl plugin"
  homepage "https://kuttl.dev"
  version "0.10.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kudobuilder/kuttl/releases/download/v0.10.0/kuttl_0.10.0_darwin_x86_64.tar.gz"
    sha256 "e2f09db57dbaaf2ee65ebe0cfb833c0e5a4f93664b5f5b654fd087185a56d0b5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kudobuilder/kuttl/releases/download/v0.10.0/kuttl_0.10.0_linux_x86_64.tar.gz"
    sha256 "b19352adafcd5004e9dc083f8d7599b142f83bb1f72b6dfa2fe42fe43a061d90"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/kudobuilder/kuttl/releases/download/v0.10.0/kuttl_0.10.0_linux_armv6.tar.gz"
    sha256 "5521659d7c13886d1cbb88fd9f1268a1647891bdb56a9595b89e072b7a2c8bbe"
  end

  depends_on "kubernetes-cli"

  def install
    bin.install "kubectl-kuttl"
  end
end
