# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KuttlCli < Formula
  desc "Interact with KUTTL via the kubectl plugin"
  homepage "https://kuttl.dev"
  version "0.18.0"

  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kudobuilder/kuttl/releases/download/v0.18.0/kuttl_0.18.0_darwin_arm64.tar.gz"
      sha256 "4a566231d2b82f99ae880dee6c84da3fde8adb10cf9a6a7844bb5c04b8e6a0e6"

      def install
        bin.install "kubectl-kuttl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kudobuilder/kuttl/releases/download/v0.18.0/kuttl_0.18.0_darwin_x86_64.tar.gz"
      sha256 "2b5850a21211e79e86c5e5a83fce7e66efdb32af9aa3b10c4732b094c508bafb"

      def install
        bin.install "kubectl-kuttl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kudobuilder/kuttl/releases/download/v0.18.0/kuttl_0.18.0_linux_armv6.tar.gz"
      sha256 "5119a527b8d750f6be6a50451b1c506d4800129f969631abdee16dc3aa784314"

      def install
        bin.install "kubectl-kuttl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kudobuilder/kuttl/releases/download/v0.18.0/kuttl_0.18.0_linux_arm64.tar.gz"
      sha256 "7718ed3d9c5877fda028c0a0bb70f99a291040941016f1501426555ac0942e49"

      def install
        bin.install "kubectl-kuttl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kudobuilder/kuttl/releases/download/v0.18.0/kuttl_0.18.0_linux_x86_64.tar.gz"
      sha256 "02ce5a08fba3dbf118b7da07ebbecf98f6af0c0234ee2f25e7be2375bed5660c"

      def install
        bin.install "kubectl-kuttl"
      end
    end
  end
end
